# Generated by Django 5.2.6 on 2025-10-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='participant_count',
            field=models.IntegerField(default=0),
        ),
    ]
