# Generated by Django 5.2.6 on 2025-10-13 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_room_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='participant_count',
        ),
    ]
