# Generated by Django 5.2.6 on 2025-10-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_remove_room_participant_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='participant_count',
            field=models.IntegerField(default=0),
        ),
    ]
